[project]
name = "edt-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdfplumber",
    "icalendar",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]
